[package]
name = "year_2023"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4"
hashbrown = "0.14"

[dev-dependencies]
test-case = "3.3"
