[package]
name = "year_2015"
version = "0.1.0"
edition = "2024"

[dependencies]
itertools = "0.14.0"
hashbrown = { version = "0.16.1", features = ["serde"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = { version = "1.0.149" }

[dev-dependencies]
test-case = "3.3.1"
